name: waveshare
description: "WaveShare - Offline File Sharing App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  flutter_riverpod: ^3.0.3
  http: ^1.1.0
  shared_preferences: ^2.2.2
  file_picker: ^8.1.4
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_blue_plus: ^1.31.5
  permission_handler: ^11.0.1
  network_info_plus: ^5.0.3
  open_file: ^3.3.2  # ADD THIS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true